version: 2.1
jobs:
    build:
      working_directory: ~/particl-desktop
      docker:
          - image: circleci/node:10.15.3-browsers
      steps:
          - checkout
          - restore_cache:
              key: dependencies-v1-{{ checksum "yarn.lock" }}
          - run:
              name: Install Dependencies
              command: yarn install --frozen-lockfile
          - save_cache:
              key: dependencies-v1-{{ checksum "yarn.lock" }}
              paths:
                  - ./yarn.lock
                  - ./node_modules
                  - $HOME/.npm/_prebuilds
                  - $HOME/.cache/electron
                  - $HOME/.cache/electron-builder

          - run:
                name: Lint Codebase
                command: yarn lint
                no_output_timeout: 2m

          - run:
                name: Setup chromium
                command: sudo apt-get install -y chromium

          - run:
                name: Test Codabase
                command: |
                    export CHROME_BIN=chromium
                    yarn travis:test
                no_output_timeout: 2m

          # - run:
          #       name: Process code coverage
          #       command: yarn coveralls
          #       no_output_timeout: 2m

          - run:
              name: Build Application
              command: yarn build --base-href="./"
              no_output_timeout: 2m
